#!/bin/sh

regex='@company\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]]
then
    echo "Your $email satisfies out Git policies."
    exit 0
else
    echo "Your $email does not satisfy our Git policies."
    exit 1
fi